// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./components/layouts/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ClassSchedulePanel: typeof import('./components/class-schedule/ClassSchedulePanel.vue')['default']
    LoginForm: typeof import('./components/layouts/LoginForm.vue')['default']
    PageBaseHeader: typeof import('./components/layouts/PageBaseHeader.vue')['default']
    PageBaseSideBar: typeof import('./components/layouts/PageBaseSideBar.vue')['default']
    PageHomeHeader: typeof import('./components/layouts/PageHomeHeader.vue')['default']
    RegisterForm: typeof import('./components/layouts/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
